### ISSUE TITLE
Sphinx warning `Unknown target name: "oneof"` in python-gke-hub ,  python-compute and python-assured-workloads

### ISSUE THREAD

**Issue by parthea** [googleapis/gapic-generator-python#1083]
For python-gke-hub, I added a workaround in owlbot.py [here](https://github.com/googleapis/python-gke-hub/blob/main/owlbot.py#L114) to solve the issue temporarily. See the build log [here](https://source.cloud.google.com/results/invocations/e0239f67-4b37-4af1-b9c8-782f69f07b3d/log) from python-gke-hub . Also see related discussion [here](https://github.com/googleapis/python-gke-hub/pull/94#discussion_r740914920).
```
sphinx.errors.SphinxWarning: /tmpfs/src/github/python-gke-hub/google/cloud/gkehub_v1/configmanagement_v1/types/configmanagement.py:docstring of google.cloud.gkehub_v1.configmanagement_v1.types.configmanagement.PolicyController:13:Unknown target name: "oneof".

Warning, treated as error:
/tmpfs/src/github/python-gke-hub/google/cloud/gkehub_v1/configmanagement_v1/types/configmanagement.py:docstring of google.cloud.gkehub_v1.configmanagement_v1.types.configmanagement.PolicyController:13:Unknown target name: "oneof".
nox > Command sphinx-build -W -T -N -b html -d docs/_build/doctrees/ docs/ docs/_build/html/ failed with exit code 2
```

This issue is also in python-compute. See the build log [here](https://source.cloud.google.com/results/invocations/4c398113-d8c0-4949-a7b5-65697d5efc54/log).

**Comment by parthea** [comment]
I'm also seeing this issue in `python-assured-workloads`. See source file [here](https://github.com/googleapis/googleapis-gen/blob/master/google/cloud/assuredworkloads/v1/assuredworkloads-v1-py/google/cloud/assuredworkloads_v1/types/assuredworkloads.py#L394). See build log [here](https://source.cloud.google.com/results/invocations/f875b3f2-77bb-49a5-b365-e4b1e52b0a7e). 

```
Traceback (most recent call last):
  File "/tmpfs/src/github/python-assured-workloads/.nox/docs/lib/python3.8/site-packages/sphinx/cmd/build.py", line 280, in build_main
    app.build(args.force_all, filenames)
  File "/tmpfs/src/github/python-assured-workloads/.nox/docs/lib/python3.8/site-packages/sphinx/application.py", line 350, in build
    self.builder.build_update()
  File "/tmpfs/src/github/python-assured-workloads/.nox/docs/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 292, in build_update
    self.build(to_build,
  File "/tmpfs/src/github/python-assured-workloads/.nox/docs/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 306, in build
    updated_docnames = set(self.read())
  File "/usr/local/lib/python3.8/contextlib.py", line 120, in __exit__
    next(self.gen)
  File "/tmpfs/src/github/python-assured-workloads/.nox/docs/lib/python3.8/site-packages/sphinx/util/logging.py", line 213, in pending_warnings
    memhandler.flushTo(logger)
  File "/tmpfs/src/github/python-assured-workloads/.nox/docs/lib/python3.8/site-packages/sphinx/util/logging.py", line 178, in flushTo
    logger.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1599, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1661, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 950, in handle
    rv = self.filter(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 811, in filter
    result = f.filter(record)
  File "/tmpfs/src/github/python-assured-workloads/.nox/docs/lib/python3.8/site-packages/sphinx/util/logging.py", line 423, in filter
    raise exc
sphinx.errors.SphinxWarning: /tmpfs/src/github/python-assured-workloads/google/cloud/assuredworkloads_v1/types/assuredworkloads.py:docstring of google.cloud.assuredworkloads_v1.types.assuredworkloads.Workload.SaaEnrollmentResponse:8:Unknown target name: "oneof".

```

**Comment by parthea** [comment]
Bumping to p3 as there is already a workaround.
