### ISSUE TITLE
IndexError when default sample file doesn't exist

### ISSUE THREAD

**Issue by sweetgiorni** [googleapis/gapic-generator-python#1217]
`generator.py` assumes the default sample file (`templates/examples/sample.py.j2`) exists and raises an exception if it doesn't. Manually creating the file resolves the issue.

#### Environment details

  - Programming language: CPython 3.9.10 
  - OS: 5.15.0-18-generic Ubuntu 22.04
  - Language runtime version:
  - Package version: `gapic-generator               0.35.10` - this seems to be the latest release on PyPI?

#### Steps to reproduce

  1. Set the `python-gapic-templates` option to an empty templates directory: ` --python_gapic_opt="python-gapic-templates=$(PWD)/templates"`
  2. Run protoc with --python_gapic_out 
  3. Am I the only one using this feature?

```
 python -m grpc_tools.protoc -I proto -I.proto/protos  -I /home/user/workspace/engineering/services/service-name/.direnv/python-3.9.10/lib/python3.9/site-packages \
        --python_gapic_opt="python-gapic-templates=/home/user/workspace/engineering/services/service-name/templates"  \
        --python_gapic_out=.proto/generated/render/ \
        .proto/protos/redacted/redacted/redacted.proto
Traceback (most recent call last):
  File "/home/user/workspace/engineering/services/service-name/.direnv/python-3.9.10/bin/protoc-gen-python_gapic", line 33, in <module>
    sys.exit(load_entry_point('gapic-generator==0.35.10', 'console_scripts', 'protoc-gen-python_gapic')())
  File "/home/user/workspace/engineering/services/service-name/.direnv/python-3.9.10/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/user/workspace/engineering/services/service-name/.direnv/python-3.9.10/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/user/workspace/engineering/services/service-name/.direnv/python-3.9.10/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user/workspace/engineering/services/service-name/.direnv/python-3.9.10/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/user/workspace/engineering/services/service-name/.direnv/python-3.9.10/lib/python3.9/site-packages/gapic/cli/generate.py", line 63, in generate
    res = generator.Generator(opts).get_response(api_schema, opts)
  File "/home/user/workspace/engineering/services/service-name/.direnv/python-3.9.10/lib/python3.9/site-packages/gapic/generator/generator.py", line 105, in get_response
    api_schema, self._env.get_template(sample_templates[0]),
IndexError: list index out of range
--python_gapic_out: protoc-gen-python_gapic: Plugin failed with status code 1.
make: *** [.vscode/proto.mk:24: .proto/compile] Error 1
```

**Comment by software-dov** [comment]
I think you may be using an old version of the generator. On `main`, the line numbering is slightly different. I'm not able to reproduce the error by just removing the `sample.py.j2` file. Can you try updating and rerunning?

**Comment by vchudnov-g** [comment]
@sweetgiorni As per Dvo's Feb 24 comment, could you try updating, rerunning, and seeing whether this issue is still present? Thanks!

**Comment by vchudnov-g** [comment]
Since we haven't heard back, I will close this issue. Feel free to re-open or file a new issue if you notice this problem again. Thanks!
