### ISSUE TITLE
undefined symbol: _Py_CheckRecursionLimit

### ISSUE THREAD

**Issue by suztomo** [googleapis/gapic-generator-python#1653]
Python runtime not being hermetic hits this `undefined symbol: _Py_CheckRecursionLimit` error.

#### Environment details

  - OS type and version: `Linux: 6.1.15-1rodete3-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.15-1rodete3 (2023-03-28) x86_64 GNU/Linux`
  - Python version: `python --version`: Python 3.7.16
  - pip version: `pip --version`: `pip 22.0.4 from /usr/local/google/home/suztomo/.pyenv/versions/3.7.16/lib/python3.7/site-packages/pip (python 3.7)`
  - `gapic-generator` version: `pip show gapic-generator`

#### Steps to reproduce

  1. `git clone github.com/googleapis/googleapis`
  2. `bazelisk build //google/monitoring/v3:monitoring-v3-py`. You get the following eror

```
suztomo@suztomo:~/googleapis$ bazelisk build //google/monitoring/v3:monitoring-v3-py
INFO: Analyzed target //google/monitoring/v3:monitoring-v3-py (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
...
ImportError: /usr/local/google/home/suztomo/.cache/bazel/_bazel_suztomo/c9601419e42dcd7b8b40ef90684cc9a1/sandbox/linux-sandbox/3/execroot/com_google_googleapis/bazel-out/k8-opt-exec-2B5CBBC6/bin/external/gapic_generator_python/gapic_plugin.runfiles/com_github_grpc_grpc/src/python/grpcio/grpc/_cython/cygrpc.so: undefined symbol: _Py_CheckRecursionLimit
--python_gapic_out: protoc-gen-python_gapic: Plugin failed with status code 1.
Target //google/monitoring/v3:monitoring-v3-py failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 1.391s, Critical Path: 1.08s
INFO: 2 processes: 2 internal.
FAILED: Build did NOT complete successfully
```

It works in another computer. Specific to this machine.

#### Code example

```python
# example
```

#### Stack trace

```
Traceback (most recent call last):
  File "/usr/local/google/home/suztomo/.cache/bazel/_bazel_suztomo/c9601419e42dcd7b8b40ef90684cc9a1/sandbox/linux-sandbox/3/execroot/com_google_googleapis/bazel-out/k8-opt-exec-2B5CBBC6/bin/external/gapic_generator_python/gapic_plugin.runfiles/gapic_generator_python/gapic/cli/generate.py", line 23, in <module>
    from gapic import generator
  File "/usr/local/google/home/suztomo/.cache/bazel/_bazel_suztomo/c9601419e42dcd7b8b40ef90684cc9a1/sandbox/linux-sandbox/3/execroot/com_google_googleapis/bazel-out/k8-opt-exec-2B5CBBC6/bin/external/gapic_generator_python/gapic_plugin.runfiles/gapic_generator_python/gapic/generator/__init__.py", line 21, in <module>
    from .generator import Generator
  File "/usr/local/google/home/suztomo/.cache/bazel/_bazel_suztomo/c9601419e42dcd7b8b40ef90684cc9a1/sandbox/linux-sandbox/3/execroot/com_google_googleapis/bazel-out/k8-opt-exec-2B5CBBC6/bin/external/gapic_generator_python/gapic_plugin.runfiles/gapic_generator_python/gapic/generator/generator.py", line 27, in <module>
    from gapic.samplegen_utils import snippet_index, snippet_metadata_pb2
  File "/usr/local/google/home/suztomo/.cache/bazel/_bazel_suztomo/c9601419e42dcd7b8b40ef90684cc9a1/sandbox/linux-sandbox/3/execroot/com_google_googleapis/bazel-out/k8-opt-exec-2B5CBBC6/bin/external/gapic_generator_python/gapic_plugin.runfiles/gapic_generator_python/gapic/samplegen_utils/snippet_index.py", line 20, in <module>
    from gapic.schema import api, metadata
  File "/usr/local/google/home/suztomo/.cache/bazel/_bazel_suztomo/c9601419e42dcd7b8b40ef90684cc9a1/sandbox/linux-sandbox/3/execroot/com_google_googleapis/bazel-out/k8-opt-exec-2B5CBBC6/bin/external/gapic_generator_python/gapic_plugin.runfiles/gapic_generator_python/gapic/schema/__init__.py", line 23, in <module>
    from gapic.schema.api import API
  File "/usr/local/google/home/suztomo/.cache/bazel/_bazel_suztomo/c9601419e42dcd7b8b40ef90684cc9a1/sandbox/linux-sandbox/3/execroot/com_google_googleapis/bazel-out/k8-opt-exec-2B5CBBC6/bin/external/gapic_generator_python/gapic_plugin.runfiles/gapic_generator_python/gapic/schema/api.py", line 42, in <module>
    import grpc  # type: ignore
  File "/usr/local/google/home/suztomo/.cache/bazel/_bazel_suztomo/c9601419e42dcd7b8b40ef90684cc9a1/sandbox/linux-sandbox/3/execroot/com_google_googleapis/bazel-out/k8-opt-exec-2B5CBBC6/bin/external/gapic_generator_python/gapic_plugin.runfiles/com_github_grpc_grpc/src/python/grpcio/grpc/__init__.py", line 22, in <module>
    from grpc import _compression
  File "/usr/local/google/home/suztomo/.cache/bazel/_bazel_suztomo/c9601419e42dcd7b8b40ef90684cc9a1/sandbox/linux-sandbox/3/execroot/com_google_googleapis/bazel-out/k8-opt-exec-2B5CBBC6/bin/external/gapic_generator_python/gapic_plugin.runfiles/com_github_grpc_grpc/src/python/grpcio/grpc/_compression.py", line 15, in <module>
    from grpc._cython import cygrpc
ImportError: /usr/local/google/home/suztomo/.cache/bazel/_bazel_suztomo/c9601419e42dcd7b8b40ef90684cc9a1/sandbox/linux-sandbox/3/execroot/com_google_googleapis/bazel-out/k8-opt-exec-2B5CBBC6/bin/external/gapic_generator_python/gapic_plugin.runfiles/com_github_grpc_grpc/src/python/grpcio/grpc/_cython/cygrpc.so: undefined symbol: _Py_CheckRecursionLimit
```

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

# Which Python is it running?

The python runtime it's trying to run is also unclear.

- With `bazelisk build //google/monitoring/v3:monitoring-v3-py --sandbox_debug --verbose_failures`, it tells the working directory and the command it failed.
  - It's linux-sandbox wrapper command to run `protoc`
  - `bazel-out/k8-opt-exec-2B5CBBC6/bin/external/com_google_protobuf/protoc --experimental_allow_proto3_optional '--plugin=protoc-gen-python_gapic=bazel-out/k8-opt-exec-2B5CBBC6/bin/external/gapic_generator_python/gapic_plugin' '--python_gapic_out=metadata,retry-config=google/monitoring/v3/monitoring_grpc_service_config.json,service-yaml=google/monitoring/v3/monitoring.yaml:bazel-out/k8-fastbuild/bin/google/monitoring/v3/monitoring_py_gapic_srcjar.srcjar.zip' '--python_gapic_opt=python-gapic-namespace=google.cloud,transport=grpc,rest-numeric-enums' '-Igoogle/monitoring/v3/alert.proto=google/monitoring/v3/alert.proto' '-Igoogle/monitoring/v3/alert_service.proto=google/monitoring/v3/alert_service.proto' '-Igoogle/monitoring/v3/common.proto=google/monitoring/v3/common.proto' '-Igoogle/monitoring/v3/dropped_labels.proto=google/monitoring/v3/dropped_labels.proto' '-Igoogle/monitoring/v3/group.proto=google/monitoring/v3/group.proto' '-Igoogle/monitoring/v3/group_service.proto=google/monitoring/v3/group_service.proto' '-Igoogle/monitoring/v3/metric.proto=google/monitoring/v3/metric.proto' '-Igoogle/monitoring/v3/metric_service.proto=google/monitoring/v3/metric_service.proto' '-Igoogle/monitoring/v3/mutation_record.proto=google/monitoring/v3/mutation_record.proto' '-Igoogle/monitoring/v3/notification.proto=google/monitoring/v3/notification.proto' '-Igoogle/monitoring/v3/notification_service.proto=google/monitoring/v3/notification_service.proto' '-Igoogle/monitoring/v3/query_service.proto=google/monitoring/v3/query_service.proto' '-Igoogle/monitoring/v3/service.proto=google/monitoring/v3/service.proto' '-Igoogle/monitoring/v3/service_service.proto=google/monitoring/v3/service_service.proto' '-Igoogle/monitoring/v3/snooze.proto=google/monitoring/v3/snooze.proto' '-Igoogle/monitoring/v3/snooze_service.proto=google/monitoring/v3/snooze_service.proto' '-Igoogle/monitoring/v3/span_context.proto=google/monitoring/v3/span_context.proto' '-Igoogle/monitoring/v3/uptime.proto=google/monitoring/v3/uptime.proto' '-Igoogle/monitoring/v3/uptime_service.proto=google/monitoring/v3/uptime_service.proto' '-Igoogle/api/annotations.proto=google/api/annotations.proto' '-Igoogle/api/http.proto=google/api/http.proto' '-Igoogle/protobuf/descriptor.proto=bazel-out/k8-fastbuild/bin/external/com_google_protobuf/_virtual_imports/descriptor_proto/google/protobuf/descriptor.proto' '-Igoogle/api/client.proto=google/api/client.proto' '-Igoogle/api/launch_stage.proto=google/api/launch_stage.proto' '-Igoogle/protobuf/duration.proto=bazel-out/k8-fastbuild/bin/external/com_google_protobuf/_virtual_imports/duration_proto/google/protobuf/duration.proto' '-Igoogle/api/distribution.proto=google/api/distribution.proto' '-Igoogle/protobuf/any.proto=bazel-out/k8-fastbuild/bin/external/com_google_protobuf/_virtual_imports/any_proto/google/protobuf/any.proto' '-Igoogle/protobuf/timestamp.proto=bazel-out/k8-fastbuild/bin/external/com_google_protobuf/_virtual_imports/timestamp_proto/google/protobuf/timestamp.proto' '-Igoogle/api/field_behavior.proto=google/api/field_behavior.proto' '-Igoogle/api/label.proto=google/api/label.proto' '-Igoogle/api/metric.proto=google/api/metric.proto' '-Igoogle/api/monitored_resource.proto=google/api/monitored_resource.proto' '-Igoogle/protobuf/struct.proto=bazel-out/k8-fastbuild/bin/external/com_google_protobuf/_virtual_imports/struct_proto/google/protobuf/struct.proto' '-Igoogle/api/resource.proto=google/api/resource.proto' '-Igoogle/rpc/status.proto=google/rpc/status.proto' '-Igoogle/type/calendar_period.proto=google/type/calendar_period.proto' '-Igoogle/protobuf/empty.proto=bazel-out/k8-fastbuild/bin/external/com_google_protobuf/_virtual_imports/empty_proto/google/protobuf/empty.proto' '-Igoogle/protobuf/field_mask.proto=bazel-out/k8-fastbuild/bin/external/com_google_protobuf/_virtual_imports/field_mask_proto/google/protobuf/field_mask.proto' '-Igoogle/protobuf/wrappers.proto=bazel-out/k8-fastbuild/bin/external/com_google_protobuf/_virtual_imports/wrappers_proto/google/protobuf/wrappers.proto' google/monitoring/v3/alert.proto google/monitoring/v3/alert_service.proto google/monitoring/v3/common.proto google/monitoring/v3/dropped_labels.proto google/monitoring/v3/group.proto google/monitoring/v3/group_service.proto google/monitoring/v3/metric.proto google/monitoring/v3/metric_service.proto google/monitoring/v3/mutation_record.proto google/monitoring/v3/notification.proto google/monitoring/v3/notification_service.proto google/monitoring/v3/query_service.proto google/monitoring/v3/service.proto google/monitoring/v3/service_service.proto google/monitoring/v3/snooze.proto google/monitoring/v3/snooze_service.proto google/monitoring/v3/span_context.proto google/monitoring/v3/uptime.proto google/monitoring/v3/uptime_service.proto`
      This gives the same error.
  - `bazel-out/k8-opt-exec-2B5CBBC6/bin/external/gapic_generator_python/gapic_plugin` has `/usr/bin/env python3` at the 1st line.

# How about bazel-bot?

Maybe I shouldn't try to setup the environment by my own. Learn how Bazel Bot runs: https://github.com/googleapis/repo-automation-bots/tree/main/packages/bazel-bot. 

```
suztomo@suztomo:~/googleapis$ mkdir -p $HOME/bazelbot-cache
suztomo@suztomo:~/googleapis$  docker run -v $HOME/googleapis:/googleapis -v $HOME/bazelbot-cache:/root/.cache  --entrypoint /bin/bash --rm -it gcr.io/repo-automation-bots/bazel-bot:latest
root@332009fd148e:/# cd googleapis
root@332009fd148e:/googleapis# bazelisk build //google/monitoring/v3:monitoring-v3-py
```

**Comment by suztomo** [comment]
I ended up using gcr.io/gapic-images/googleapis:20230301.
