### ISSUE TITLE
docs build for goldens failing

### ISSUE THREAD

**Issue by parthea** [googleapis/gapic-generator-python#1714]
Running the `docs` build in any of the [generated golden clients](https://github.com/googleapis/gapic-generator-python/tree/main/tests/integration/goldens) fails.

See example below for the `credentials` client. I've confirmed that the issue is resolved if we upgrade `sphinx`.

```
(py39) partheniou@partheniou-vm-3:~/git/gapic-generator-python/tests/integration/goldens/credentials$ nox -s docs
/usr/local/google/home/partheniou/.pyenv/versions/py39/lib/python3.9/site-packages/setuptools/dist.py:945: SetuptoolsDeprecationWarning: The namespace_packages parameter is deprecated.
!!

        ********************************************************************************
        Please replace its usage with implicit namespaces (PEP 420).

        See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages for details.
        ********************************************************************************

!!
  ep.load()(self, ep.name, value)
nox > Running session docs
nox > Creating virtual environment (virtualenv) using python3.11 in .nox/docs
nox > python -m pip install -e .
nox > python -m pip install sphinx==4.0.1 alabaster recommonmark
nox > sphinx-build -W -T -N -b html -d docs/_build/doctrees/ docs/ docs/_build/html/
Traceback (most recent call last):
  File "/usr/local/google/home/partheniou/git/gapic-generator-python/tests/integration/goldens/credentials/.nox/docs/bin/sphinx-build", line 5, in <module>
    from sphinx.cmd.build import main
  File "/usr/local/google/home/partheniou/git/gapic-generator-python/tests/integration/goldens/credentials/.nox/docs/lib/python3.11/site-packages/sphinx/cmd/build.py", line 25, in <module>
    from sphinx.application import Sphinx
  File "/usr/local/google/home/partheniou/git/gapic-generator-python/tests/integration/goldens/credentials/.nox/docs/lib/python3.11/site-packages/sphinx/application.py", line 31, in <module>
    from sphinx.config import Config
  File "/usr/local/google/home/partheniou/git/gapic-generator-python/tests/integration/goldens/credentials/.nox/docs/lib/python3.11/site-packages/sphinx/config.py", line 21, in <module>
    from sphinx.util import logging
  File "/usr/local/google/home/partheniou/git/gapic-generator-python/tests/integration/goldens/credentials/.nox/docs/lib/python3.11/site-packages/sphinx/util/__init__.py", line 41, in <module>
    from sphinx.util.typing import PathMatcher
  File "/usr/local/google/home/partheniou/git/gapic-generator-python/tests/integration/goldens/credentials/.nox/docs/lib/python3.11/site-packages/sphinx/util/typing.py", line 37, in <module>
    from types import Union as types_Union
ImportError: cannot import name 'Union' from 'types' (/usr/lib/python3.11/types.py)
nox > Command sphinx-build -W -T -N -b html -d docs/_build/doctrees/ docs/ docs/_build/html/ failed with exit code 1
nox > Session docs failed.
```

**Comment by parthea** [comment]
The error above was resolved by upgrading sphinx to 7.0.1

After upgrading, there is a different error
```
Invalid configuration value found: 'language = None'. Update your configuration to a valid language code. Falling back to 'en' (English).
```

```
(py39) partheniou@partheniou-vm-3:~/git/gapic-generator-python/tests/integration/goldens/credentials$ nox -s docs
/usr/local/google/home/partheniou/.pyenv/versions/py39/lib/python3.9/site-packages/setuptools/dist.py:945: SetuptoolsDeprecationWarning: The namespace_packages parameter is deprecated.
!!

        ********************************************************************************
        Please replace its usage with implicit namespaces (PEP 420).

        See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages for details.
        ********************************************************************************

!!
  ep.load()(self, ep.name, value)
nox > Running session docs
nox > Creating virtual environment (virtualenv) using python3.11 in .nox/docs
nox > python -m pip install -e .
nox > python -m pip install sphinx==7.0.1 alabaster recommonmark
nox > sphinx-build -W -T -N -b html -d docs/_build/doctrees/ docs/ docs/_build/html/
Running Sphinx v7.0.1

Traceback (most recent call last):
  File "/usr/local/google/home/partheniou/git/gapic-generator-python/tests/integration/goldens/credentials/.nox/docs/lib/python3.11/site-packages/sphinx/cmd/build.py", line 280, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/google/home/partheniou/git/gapic-generator-python/tests/integration/goldens/credentials/.nox/docs/lib/python3.11/site-packages/sphinx/application.py", line 207, in __init__
    self.config = Config.read(self.confdir, confoverrides or {}, self.tags)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/google/home/partheniou/git/gapic-generator-python/tests/integration/goldens/credentials/.nox/docs/lib/python3.11/site-packages/sphinx/config.py", line 184, in read
    logger.warning(__("Invalid configuration value found: 'language = None'. "
  File "/usr/lib/python3.11/logging/__init__.py", line 1855, in warning
    self.log(WARNING, msg, *args, **kwargs)
  File "/usr/local/google/home/partheniou/git/gapic-generator-python/tests/integration/goldens/credentials/.nox/docs/lib/python3.11/site-packages/sphinx/util/logging.py", line 124, in log
    super().log(level, msg, *args, **kwargs)
  File "/usr/lib/python3.11/logging/__init__.py", line 1887, in log
    self.logger.log(level, msg, *args, **kwargs)
  File "/usr/lib/python3.11/logging/__init__.py", line 1559, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/lib/python3.11/logging/__init__.py", line 1634, in _log
    self.handle(record)
  File "/usr/lib/python3.11/logging/__init__.py", line 1644, in handle
    self.callHandlers(record)
  File "/usr/lib/python3.11/logging/__init__.py", line 1706, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python3.11/logging/__init__.py", line 974, in handle
    rv = self.filter(record)
         ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/logging/__init__.py", line 830, in filter
    result = f.filter(record)
             ^^^^^^^^^^^^^^^^
  File "/usr/local/google/home/partheniou/git/gapic-generator-python/tests/integration/goldens/credentials/.nox/docs/lib/python3.11/site-packages/sphinx/util/logging.py", line 424, in filter
    raise exc
sphinx.errors.SphinxWarning: Invalid configuration value found: 'language = None'. Update your configuration to a valid language code. Falling back to 'en' (English).

Warning, treated as error:
Invalid configuration value found: 'language = None'. Update your configuration to a valid language code. Falling back to 'en' (English).
nox > Command sphinx-build -W -T -N -b html -d docs/_build/doctrees/ docs/ docs/_build/html/ failed with exit code 2
nox > Session docs failed.
```

**Comment by parthea** [comment]
After changing `language = None` to  `language = 'en'` as indicated in the error message, there is a different error
```
(py39) partheniou@partheniou-vm-3:~/git/gapic-generator-python/tests/integration/goldens/credentials$ nox -s docs
/usr/local/google/home/partheniou/.pyenv/versions/py39/lib/python3.9/site-packages/setuptools/dist.py:945: SetuptoolsDeprecationWarning: The namespace_packages parameter is deprecated.
!!

        ********************************************************************************
        Please replace its usage with implicit namespaces (PEP 420).

        See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages for details.
        ********************************************************************************

!!
  ep.load()(self, ep.name, value)
nox > Running session docs
nox > Creating virtual environment (virtualenv) using python3.11 in .nox/docs
nox > python -m pip install -e .
nox > python -m pip install sphinx==7.0.1 alabaster recommonmark
nox > sphinx-build -W -T -N -b html -d docs/_build/doctrees/ docs/ docs/_build/html/
Running Sphinx v7.0.1
making output directory... done

Traceback (most recent call last):
  File "/usr/local/google/home/partheniou/git/gapic-generator-python/tests/integration/goldens/credentials/.nox/docs/lib/python3.11/site-packages/sphinx/cmd/build.py", line 280, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/google/home/partheniou/git/gapic-generator-python/tests/integration/goldens/credentials/.nox/docs/lib/python3.11/site-packages/sphinx/application.py", line 253, in __init__
    self.events.emit('config-inited', self.config)
  File "/usr/local/google/home/partheniou/git/gapic-generator-python/tests/integration/goldens/credentials/.nox/docs/lib/python3.11/site-packages/sphinx/events.py", line 96, in emit
    results.append(listener.handler(self.app, *args))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/google/home/partheniou/git/gapic-generator-python/tests/integration/goldens/credentials/.nox/docs/lib/python3.11/site-packages/sphinx/builders/html/__init__.py", line 1283, in validate_html_static_path
    logger.warning(__('html_static_path entry %r does not exist'), entry)
  File "/usr/lib/python3.11/logging/__init__.py", line 1855, in warning
    self.log(WARNING, msg, *args, **kwargs)
  File "/usr/local/google/home/partheniou/git/gapic-generator-python/tests/integration/goldens/credentials/.nox/docs/lib/python3.11/site-packages/sphinx/util/logging.py", line 124, in log
    super().log(level, msg, *args, **kwargs)
  File "/usr/lib/python3.11/logging/__init__.py", line 1887, in log
    self.logger.log(level, msg, *args, **kwargs)
  File "/usr/lib/python3.11/logging/__init__.py", line 1559, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/lib/python3.11/logging/__init__.py", line 1634, in _log
    self.handle(record)
  File "/usr/lib/python3.11/logging/__init__.py", line 1644, in handle
    self.callHandlers(record)
  File "/usr/lib/python3.11/logging/__init__.py", line 1706, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python3.11/logging/__init__.py", line 974, in handle
    rv = self.filter(record)
         ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/logging/__init__.py", line 830, in filter
    result = f.filter(record)
             ^^^^^^^^^^^^^^^^
  File "/usr/local/google/home/partheniou/git/gapic-generator-python/tests/integration/goldens/credentials/.nox/docs/lib/python3.11/site-packages/sphinx/util/logging.py", line 424, in filter
    raise exc
sphinx.errors.SphinxWarning: html_static_path entry '_static' does not exist
```
