### ISSUE TITLE
Error when running vision API

### ISSUE THREAD

**Issue by danoscarmike** [googleapis/gapic-generator-python#183]
I get the following TypeError associated with an rpc that returns a long running operation. I can successfully generate for other services (e.g. Cloud Scheduler which has no such rpc) 

I see the same error when running either locally (Python 3.7.4 in venv on Mac) or via Docker.

Full traceback:
```
google/cloud/vision/v1/image_annotator.proto:27:1: warning: Import google/protobuf/field_mask.proto but not used.
Traceback (most recent call last):
  File "/Users/danom/code/pycode/env/bin/protoc-gen-python_gapic", line 11, in <module>
    load_entry_point('gapic-generator', 'console_scripts', 'protoc-gen-python_gapic')()
  File "/Users/danom/code/pycode/env/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/danom/code/pycode/env/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/danom/code/pycode/env/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/danom/code/pycode/env/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/danom/code/pycode/client_gen_cloud/gapic-generator-python/gapic/cli/generate.py", line 59, in generate
    api_schema = api.API.build(req.proto_file, opts=opts, package=package)
  File "/Users/danom/code/pycode/client_gen_cloud/gapic-generator-python/gapic/schema/api.py", line 211, in build
    prior_protos=protos,
  File "/Users/danom/code/pycode/client_gen_cloud/gapic-generator-python/gapic/schema/api.py", line 363, in __init__
    address=self.address, path=(6,))
  File "/Users/danom/code/pycode/client_gen_cloud/gapic-generator-python/gapic/schema/api.py", line 448, in _load_children
    wrapped = loader(child, address=address, path=path + (i,))
  File "/Users/danom/code/pycode/client_gen_cloud/gapic-generator-python/gapic/schema/api.py", line 649, in _load_service
    path=path + (2,),
  File "/Users/danom/code/pycode/client_gen_cloud/gapic-generator-python/gapic/schema/api.py", line 524, in _get_methods
    f'rpc {meth_pb.name} returns a google.longrunning.'
TypeError: rpc ImportProductSets returns a google.longrunning.Operation, but is missing a response type or metadata type.
--python_gapic_out: protoc-gen-python_gapic: Plugin failed with status code 1.
```

**Comment by software-dov** [comment]
The python microgenerator does not read in gapic yaml files, and the only way for it to know the real response and metadata types for a longrunning operation is through annotations in the service proto files. This error indicates that the `ImportProductSets` method isn't annotated in this manner.
See https://aip.dev/151 for a fuller description of the annotation.

**Comment by danoscarmike** [comment]
Thanks @software-dov. I had a suspicion that it was related to proto annotations but didn't know enough about them.

So, for clarity, if the proto was updated [here](https://github.com/googleapis/googleapis/blob/4bb50a3e4c8d49d1cec1a98434cccaeaec55a886/google/cloud/vision/v1/product_search_service.proto#L307) in accordance with the AIP you shared, the microgenerator should work?

Are the annotations also backward compatible with the original [gapic-generator](https://github.com/googleapis/gapic-generator)?

**Comment by lukesneeringer** [comment]
Yes, that is correct, and yes, gapic-generator reads the annotations.

**Comment by software-dov** [comment]
IIUC annotations are backward compatible with the original generator. They are treated as options that the original generator just ignores.

**Comment by lukesneeringer** [comment]
Actually the original generator now honors them.

**Comment by danoscarmike** [comment]
Awesome! And awesome work BTW. I loved checking it out. Docs were great, no issues with environment, all really cool!
