### ISSUE TITLE
Generator Getting Started Fails (Docker)

### ISSUE THREAD

**Issue by nnegrey** [googleapis/gapic-generator-python#186]
The Getting Started for Docker fails. 

Command:
```
docker run \
        --mount type=bind,source=$(pwd)/google/cloud/vision/v1/,destination=/in/google/cloud/vision/v1/,readonly \
        --mount type=bind,source=$(pwd)/dest/,destination=/out/ \
        --rm \
        --user $UID \
        gcr.io/gapic-images/gapic-generator-python
```

Output:
```
google/cloud/vision/v1/image_annotator.proto: warning: Import google/protobuf/field_mask.proto but not used.
Traceback (most recent call last):
  File "/usr/local/bin/protoc-gen-python_gapic", line 10, in <module>
    sys.exit(generate())
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/gapic/cli/generate.py", line 59, in generate
    api_schema = api.API.build(req.proto_file, opts=opts, package=package)
  File "/usr/local/lib/python3.7/site-packages/gapic/schema/api.py", line 211, in build
    prior_protos=protos,
  File "/usr/local/lib/python3.7/site-packages/gapic/schema/api.py", line 363, in __init__
    address=self.address, path=(6,))
  File "/usr/local/lib/python3.7/site-packages/gapic/schema/api.py", line 448, in _load_children
    wrapped = loader(child, address=address, path=path + (i,))
  File "/usr/local/lib/python3.7/site-packages/gapic/schema/api.py", line 649, in _load_service
    path=path + (2,),
  File "/usr/local/lib/python3.7/site-packages/gapic/schema/api.py", line 524, in _get_methods
    f'rpc {meth_pb.name} returns a google.longrunning.'
TypeError: rpc ImportProductSets returns a google.longrunning.Operation, but is missing a response type or metadata type.
--python_gapic_out: protoc-gen-python_gapic: Plugin failed with status code 1.
```

 Proto Field:
```
// Asynchronous API that imports a list of reference images to specified
  // product sets based on a list of image information.
  //
  // The [google.longrunning.Operation][google.longrunning.Operation] API can be
  // used to keep track of the progress and results of the request.
  // `Operation.metadata` contains `BatchOperationMetadata`. (progress)
  // `Operation.response` contains `ImportProductSetsResponse`. (results)
  //
  // The input source of this method is a csv file on Google Cloud Storage.
  // For the format of the csv file please see
  // [ImportProductSetsGcsSource.csv_file_uri][google.cloud.vision.v1.ImportProductSetsGcsSource.csv_file_uri].
  rpc ImportProductSets(ImportProductSetsRequest)
      returns (google.longrunning.Operation) {
    option (google.api.http) = {
      post: "/v1/{parent=projects/*/locations/*}/productSets:import"
      body: "*"
    };
  }
```

**Comment by busunkim96** [comment]
@nnegrey See #183. I think the LROs need annotations.

**Comment by nnegrey** [comment]
Gotcha, thanks. Closing.
