### ISSUE TITLE
Failing generation: cursor = self.fields[field_path[0]] KeyError: 'options'

### ISSUE THREAD

**Issue by busunkim96** [googleapis/gapic-generator-python#405]
Generation for [BigQuery Connections v1beta1](https://github.com/googleapis/googleapis/blob/master/google/cloud/bigquery/connection/v1beta1/connection.proto) is failing. @steffnay is currently working on this launch.

```2020-05-04 17:07:52,639 synthtool > Generating code for: google/cloud/bigquery/connection/v1beta1.
2020-05-04 17:07:55,303 synthtool > Failed executing docker run --mount type=bind,source=/usr/local/google/home/busunkim/.cache/synthtool/googleapis/google/cloud/bigquery/connection/v1beta1/,destination=/in/google/cloud/bigquery/connection/v1beta1/,readonly --mount type=bind,source=/tmp/tmpsamwhpou/,destination=/out/ --rm --user 583508 gcr.io/gapic-images/gapic-generator-python:latest:

Traceback (most recent call last):
  File "/usr/local/bin/protoc-gen-python_gapic", line 8, in <module>
    sys.exit(generate())
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/gapic/cli/generate.py", line 58, in generate
    api_schema = api.API.build(req.proto_file, opts=opts, package=package)
  File "/usr/local/lib/python3.7/site-packages/gapic/schema/api.py", line 276, in build
    for name, proto in pre_protos.items()
  File "/usr/local/lib/python3.7/site-packages/gapic/schema/api.py", line 276, in <dictcomp>
    for name, proto in pre_protos.items()
  File "/usr/local/lib/python3.7/site-packages/gapic/schema/api.py", line 86, in build
    load_services=load_services
  File "/usr/local/lib/python3.7/site-packages/gapic/schema/api.py", line 492, in proto
    for k, v in naive.services.items()
  File "/usr/local/lib/python3.7/site-packages/gapic/schema/api.py", line 492, in <genexpr>
    for k, v in naive.services.items()
  File "/usr/local/lib/python3.7/site-packages/gapic/schema/wrappers.py", line 911, in with_context
    for k, v in self.methods.items()
  File "/usr/local/lib/python3.7/site-packages/gapic/schema/wrappers.py", line 911, in <genexpr>
    for k, v in self.methods.items()
  File "/usr/local/lib/python3.7/site-packages/gapic/utils/cache.py", line 39, in inner
    self._cached_values[fx.__name__] = fx(self)
  File "/usr/local/lib/python3.7/site-packages/gapic/schema/wrappers.py", line 654, in flattened_fields
    for sig in signatures
  File "/usr/local/lib/python3.7/site-packages/gapic/schema/wrappers.py", line 655, in <genexpr>
    for name_and_field in filter_fields(sig)
  File "/usr/local/lib/python3.7/site-packages/gapic/schema/wrappers.py", line 643, in filter_fields
    field = self.input.get_field(*name.split('.'))
  File "/usr/local/lib/python3.7/site-packages/gapic/schema/wrappers.py", line 342, in get_field
    cursor = self.fields[field_path[0]]
KeyError: 'options'
--python_gapic_out: protoc-gen-python_gapic: Plugin failed with status code 1.```
```

Suspected cause:
```
  // Gets the access control policy for a resource.
  // Returns an empty policy if the resource exists and does not have a policy
  // set.
  rpc GetIamPolicy(google.iam.v1.GetIamPolicyRequest) returns (google.iam.v1.Policy) {
    option (google.api.http) = {
      post: "/v1beta1/{resource=projects/*/locations/*/connections/*}:getIamPolicy"
      body: "*"
    };
    option (google.api.method_signature) = "resource,options";
  }
```

**Comment by busunkim96** [comment]
The use of `google.api.method_signature` looks correct to me. Maybe `GetIamPolicyRequest` being defined in the IAM protos is problematic for the generator?

https://github.com/googleapis/googleapis/blob/218164b3deba1075979c9dca5f71461379e42dd1/google/iam/v1/iam_policy.proto#L113-L123

```
// Request message for `GetIamPolicy` method.
message GetIamPolicyRequest {
  // REQUIRED: The resource for which the policy is being requested.
  // See the operation documentation for the appropriate value for this field.
  string resource = 1 [
    (google.api.field_behavior) = REQUIRED,
    (google.api.resource_reference).type = "*"];

  // OPTIONAL: A `GetPolicyOptions` object for specifying options to
  // `GetIamPolicy`. This field is only used by Cloud IAM.
  GetPolicyOptions options = 2;
}
```

Steffany has successfully generated the library in Java.

**Comment by busunkim96** [comment]
I looked at the [Dockerfile](https://github.com/googleapis/gapic-generator-python/blob/master/Dockerfile) and I think the issue is an old copy of api-common-protos (http://gcr.io/gapic-images/api-common-protos:0.1.0). 

https://github.com/googleapis/gapic-generator-python/blob/903371553e5ad55c3136dfd88f0748ef1f20c900/Dockerfile#L10-L11

The image was published [April 2019](https://pantheon.corp.google.com/gcr/images/gapic-images/GLOBAL/api-common-protos@sha256:a21d24e20497fc89b6da5f471b50aeef6b287d1980011f2417b34cd04f1263bb/details?tab=info) and `GetIamPolicyRequest` didn't have 'options' at the time. 

Opened #412 to address this.
