### ISSUE TITLE
RPC fails to execute: google.api_core.exceptions.MethodNotImplemented: 501 GRPC target method can't be resolved.

### ISSUE THREAD

**Issue by crwilcox** [googleapis/gapic-generator-python#489]
I have an odd failure while using the new generated surface. The code isn't able to execute an RPC.

```
document_pb = firestore_api.get_document(
                request={
                    "name": self._document_path,
                    "mask": mask,
                    "transaction": _helpers.get_transaction_id(transaction),
                },
                metadata=self._client._rpc_metadata,
            )
```

```
'name':'projects/crwgoog-test/databases/(default)/documents/created/for-get-1593235930790'
'mask':None
'transaction':None
```

It fails on this line  while making the RPC
https://github.com/googleapis/python-firestore/pull/63/files#diff-02069167382e32cba90fe5b9e98f8893R272

```
google/cloud/firestore_v1/document.py:449: in get
    document_pb = firestore_api.get_document(
google/cloud/firestore_v1/services/firestore/client.py:272: in get_document
    response = rpc(request, retry=retry, timeout=timeout, metadata=metadata,)
.nox/unit-3-8/lib/python3.8/site-packages/google/api_core/gapic_v1/method.py:143: in __call__
    return wrapped_func(*args, **kwargs)
.nox/unit-3-8/lib/python3.8/site-packages/google/api_core/grpc_helpers.py:59: in error_remapped_callable
    six.raise_from(exceptions.from_grpc_error(exc), exc)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

value = None
from_value = <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNIMPLEMENTED
	details = "GRPC target method can'.../core/lib/surface/call.cc","file_line":1055,"grpc_message":"GRPC target method can't be resolved.","grpc_status":12}"
>

>   ???
E   google.api_core.exceptions.MethodNotImplemented: 501 GRPC target method can't be resolved.

```

Setup.py Deps:
```
dependencies = [
    "google-api-core[grpc] >= 1.17.2, < 2.0.0dev",
    "google-cloud-core >= 1.0.3, < 2.0dev",
    "pytz",
    "libcst >= 0.2.5",
    "proto-plus >= 0.4.0",
]
```

**Comment by crwilcox** [comment]
Additional details: code at https://github.com/googleapis/python-firestore/pull/63/commits/87ca1429c91c7fa71f7133b7c1ff0477b99c7c72

```
>>> from google.cloud import firestore_v1
>>> gen_client = firestore_v1.services.firestore.FirestoreClient()
>>> gen_client.list_collection_ids()
```

```
Traceback (most recent call last):
  File "/Users/crwilcox/workspace/googleapis/python-firestore/.nox/unit-3-8/lib/python3.8/site-packages/google/api_core/grpc_helpers.py", line 57, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/Users/crwilcox/workspace/googleapis/python-firestore/.nox/unit-3-8/lib/python3.8/site-packages/grpc/_channel.py", line 826, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/crwilcox/workspace/googleapis/python-firestore/.nox/unit-3-8/lib/python3.8/site-packages/grpc/_channel.py", line 729, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNIMPLEMENTED
	details = "GRPC target method can't be resolved."
	debug_error_string = "{"created":"@1594265254.552425000","description":"Error received from peer ipv4:172.217.3.170:443","file":"src/core/lib/surface/call.cc","file_line":1055,"grpc_message":"GRPC target method can't be resolved.","grpc_status":12}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/crwilcox/workspace/googleapis/python-firestore/google/cloud/firestore_v1/services/firestore/client.py", line 1051, in list_collection_ids
    response = rpc(request, retry=retry, timeout=timeout, metadata=metadata,)
  File "/Users/crwilcox/workspace/googleapis/python-firestore/.nox/unit-3-8/lib/python3.8/site-packages/google/api_core/gapic_v1/method.py", line 143, in __call__
    return wrapped_func(*args, **kwargs)
  File "/Users/crwilcox/workspace/googleapis/python-firestore/.nox/unit-3-8/lib/python3.8/site-packages/google/api_core/grpc_helpers.py", line 59, in error_remapped_callable
    six.raise_from(exceptions.from_grpc_error(exc), exc)
  File "<string>", line 3, in raise_from
google.api_core.exceptions.MethodNotImplemented: 501 GRPC target method can't be resolved.
```

**Comment by crwilcox** [comment]
Closing. this is intertwined with namespaces. rpc is google.firestore, though google.cloud.firestore rename was being applied.

**Comment by danoscarmike** [comment]
@crwilcox did you figure a work around? I'm getting the same failure with Translation API, having made synthtool moves and replaces to override google.cloud.translation with google.cloud.translate.

**Comment by crwilcox** [comment]
@danoscarmike yep. Some of those are references to the location of the api surface, not the namespace, which is *tricky*.

here are the replacements that worked for python:
```
for version in admin_versions:
    library = gapic.py_library(
        service="firestore_admin",
        version=version,
        # bazel_target=f"//google/firestore/admin/{version}:firestore-admin-{version}-py",
        # include_protos=True,
        proto_path=f"google/firestore/admin/{version}",
    )
    s.move(library / f"google/firestore/admin_{version}", f"google/cloud/firestore_admin_{version}")
    s.move(library / "tests")
    s.move(library / "scripts")

    s.replace(
        f"google/cloud/**/*.py",
        f"google.firestore.admin_v1",
        f"google.cloud.firestore_admin_v1",
    )
    s.replace(
        f"tests/unit/gapic/**/*.py",
        f"google.firestore.admin_v1",
        f"google.cloud.firestore_admin_v1",
    )
    s.replace(
        f"google/cloud/firestore_admin_v1/services/firestore_admin/client.py",
        f"from google.api_core import operation as ga_operation",
        f"from google.api_core import operation as ga_operation\nfrom google.api_core import operation",
    )
```

here is an instance of where you *don't* want to edit.

```
__protobuf__ = proto.module(
    package="google.firestore.v1",
```

**Comment by danoscarmike** [comment]
Thank you, thank you! I've almost certainly interfered with the package name.
