### ISSUE TITLE
cloud build client lib generation failed with v0.33.3

### ISSUE THREAD

**Issue by arithmetic1728** [googleapis/gapic-generator-python#600]
How to reproduce:
1. download python-cloudbuild and googleapis repo
2. change the `gapic-generator-python` version in googleapis repo WORKSPACE file to 0.33.3
3. cd to python-cloudbuild repo, `export SYNTHTOOL_GOOGLEAPIS=/path/to/googleapis`
4. run `python3 -m synthtool`

```
Traceback (most recent call last):
  File "/usr/local/google/home/sijunliu/.cache/bazel/_bazel_sijunliu/d5034438c20c551b46737f25375e0df0/sandbox/linux-sandbox/5/execroot/com_google_googleapis/bazel-out/host/bin/external/gapic_generator_python/gapic_plugin.runfiles/gapic_generator_python/gapic/cli/generate_with_pandoc.py", line 9, in <module>
    generate.generate()
  File "/usr/local/google/home/sijunliu/.cache/bazel/_bazel_sijunliu/d5034438c20c551b46737f25375e0df0/sandbox/linux-sandbox/5/execroot/com_google_googleapis/bazel-out/host/bin/external/gapic_generator_python/gapic_plugin.runfiles/gapic_generator_python_pip_deps_pypi__click_7_1_2/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/google/home/sijunliu/.cache/bazel/_bazel_sijunliu/d5034438c20c551b46737f25375e0df0/sandbox/linux-sandbox/5/execroot/com_google_googleapis/bazel-out/host/bin/external/gapic_generator_python/gapic_plugin.runfiles/gapic_generator_python_pip_deps_pypi__click_7_1_2/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/google/home/sijunliu/.cache/bazel/_bazel_sijunliu/d5034438c20c551b46737f25375e0df0/sandbox/linux-sandbox/5/execroot/com_google_googleapis/bazel-out/host/bin/external/gapic_generator_python/gapic_plugin.runfiles/gapic_generator_python_pip_deps_pypi__click_7_1_2/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/google/home/sijunliu/.cache/bazel/_bazel_sijunliu/d5034438c20c551b46737f25375e0df0/sandbox/linux-sandbox/5/execroot/com_google_googleapis/bazel-out/host/bin/external/gapic_generator_python/gapic_plugin.runfiles/gapic_generator_python_pip_deps_pypi__click_7_1_2/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/google/home/sijunliu/.cache/bazel/_bazel_sijunliu/d5034438c20c551b46737f25375e0df0/sandbox/linux-sandbox/5/execroot/com_google_googleapis/bazel-out/host/bin/external/gapic_generator_python/gapic_plugin.runfiles/gapic_generator_python/gapic/cli/generate.py", line 58, in generate
    api_schema = api.API.build(req.proto_file, opts=opts, package=package)
  File "/usr/local/google/home/sijunliu/.cache/bazel/_bazel_sijunliu/d5034438c20c551b46737f25375e0df0/sandbox/linux-sandbox/5/execroot/com_google_googleapis/bazel-out/host/bin/external/gapic_generator_python/gapic_plugin.runfiles/gapic_generator_python/gapic/schema/api.py", line 270, in build
    protos: Dict[str, Proto] = {
  File "/usr/local/google/home/sijunliu/.cache/bazel/_bazel_sijunliu/d5034438c20c551b46737f25375e0df0/sandbox/linux-sandbox/5/execroot/com_google_googleapis/bazel-out/host/bin/external/gapic_generator_python/gapic_plugin.runfiles/gapic_generator_python/gapic/schema/api.py", line 271, in <dictcomp>
    name: Proto.build(
  File "/usr/local/google/home/sijunliu/.cache/bazel/_bazel_sijunliu/d5034438c20c551b46737f25375e0df0/sandbox/linux-sandbox/5/execroot/com_google_googleapis/bazel-out/host/bin/external/gapic_generator_python/gapic_plugin.runfiles/gapic_generator_python/gapic/schema/api.py", line 82, in build
    return _ProtoBuilder(
  File "/usr/local/google/home/sijunliu/.cache/bazel/_bazel_sijunliu/d5034438c20c551b46737f25375e0df0/sandbox/linux-sandbox/5/execroot/com_google_googleapis/bazel-out/host/bin/external/gapic_generator_python/gapic_plugin.runfiles/gapic_generator_python/gapic/schema/api.py", line 508, in proto
    services=collections.OrderedDict(
  File "/usr/local/google/home/sijunliu/.cache/bazel/_bazel_sijunliu/d5034438c20c551b46737f25375e0df0/sandbox/linux-sandbox/5/execroot/com_google_googleapis/bazel-out/host/bin/external/gapic_generator_python/gapic_plugin.runfiles/gapic_generator_python/gapic/schema/api.py", line 511, in <genexpr>
    (k, v.with_context(collisions=v.names))
  File "/usr/local/google/home/sijunliu/.cache/bazel/_bazel_sijunliu/d5034438c20c551b46737f25375e0df0/sandbox/linux-sandbox/5/execroot/com_google_googleapis/bazel-out/host/bin/external/gapic_generator_python/gapic_plugin.runfiles/gapic_generator_python/gapic/schema/wrappers.py", line 1000, in with_context
    methods=collections.OrderedDict(
  File "/usr/local/google/home/sijunliu/.cache/bazel/_bazel_sijunliu/d5034438c20c551b46737f25375e0df0/sandbox/linux-sandbox/5/execroot/com_google_googleapis/bazel-out/host/bin/external/gapic_generator_python/gapic_plugin.runfiles/gapic_generator_python/gapic/schema/wrappers.py", line 1004, in <genexpr>
    collisions=collisions | frozenset(v.flattened_fields.keys()))
  File "/usr/local/google/home/sijunliu/.cache/bazel/_bazel_sijunliu/d5034438c20c551b46737f25375e0df0/sandbox/linux-sandbox/5/execroot/com_google_googleapis/bazel-out/host/bin/external/gapic_generator_python/gapic_plugin.runfiles/gapic_generator_python/gapic/utils/cache.py", line 39, in inner
    self._cached_values[fx.__name__] = fx(self)
  File "/usr/local/google/home/sijunliu/.cache/bazel/_bazel_sijunliu/d5034438c20c551b46737f25375e0df0/sandbox/linux-sandbox/5/execroot/com_google_googleapis/bazel-out/host/bin/external/gapic_generator_python/gapic_plugin.runfiles/gapic_generator_python/gapic/schema/wrappers.py", line 727, in flattened_fields
    answer: Dict[str, Field] = collections.OrderedDict(
  File "/usr/local/google/home/sijunliu/.cache/bazel/_bazel_sijunliu/d5034438c20c551b46737f25375e0df0/sandbox/linux-sandbox/5/execroot/com_google_googleapis/bazel-out/host/bin/external/gapic_generator_python/gapic_plugin.runfiles/gapic_generator_python/gapic/schema/wrappers.py", line 730, in <genexpr>
    for name_and_field in filter_fields(sig)
  File "/usr/local/google/home/sijunliu/.cache/bazel/_bazel_sijunliu/d5034438c20c551b46737f25375e0df0/sandbox/linux-sandbox/5/execroot/com_google_googleapis/bazel-out/host/bin/external/gapic_generator_python/gapic_plugin.runfiles/gapic_generator_python/gapic/schema/wrappers.py", line 718, in filter_fields
    field = self.input.get_field(*name.split('.'))
  File "/usr/local/google/home/sijunliu/.cache/bazel/_bazel_sijunliu/d5034438c20c551b46737f25375e0df0/sandbox/linux-sandbox/5/execroot/com_google_googleapis/bazel-out/host/bin/external/gapic_generator_python/gapic_plugin.runfiles/gapic_generator_python/gapic/schema/wrappers.py", line 391, in get_field
    cursor = self.fields[field_path[0]]
KeyError: 'id'
--python_gapic_out: protoc-gen-python_gapic: Plugin failed with status code 1.
Target //google/devtools/cloudbuild/v1:devtools-cloudbuild-v1-py failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 3.256s, Critical Path: 0.74s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully
```

**Comment by software-dov** [comment]
Fixed by #602
