### ISSUE TITLE
Sphinx: unexpected section header

### ISSUE THREAD

**Issue by larkee** [googleapis/gapic-generator-python#633]
When running `nox -s docs`, it fails with the following traceback:
```
Traceback (most recent call last):
  File "~/python-spanner/.nox/docs/lib/python3.8/site-packages/sphinx/cmd/build.py", line 280, in build_main
    app.build(args.force_all, filenames)
  File "~/python-spanner/.nox/docs/lib/python3.8/site-packages/sphinx/application.py", line 348, in build
    self.builder.build_update()
  File "~/python-spanner/.nox/docs/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 297, in build_update
    self.build(to_build,
  File "~/python-spanner/.nox/docs/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 311, in build
    updated_docnames = set(self.read())
  File "~/.pyenv/versions/3.8-dev/lib/python3.8/contextlib.py", line 120, in __exit__
    next(self.gen)
  File "~/python-spanner/.nox/docs/lib/python3.8/site-packages/sphinx/util/logging.py", line 213, in pending_warnings
    memhandler.flushTo(logger)
  File "~/python-spanner/.nox/docs/lib/python3.8/site-packages/sphinx/util/logging.py", line 178, in flushTo
    logger.handle(record)
  File "~/.pyenv/versions/3.8-dev/lib/python3.8/logging/__init__.py", line 1587, in handle
    self.callHandlers(record)
  File "~/.pyenv/versions/3.8-dev/lib/python3.8/logging/__init__.py", line 1649, in callHandlers
    hdlr.handle(record)
  File "~/.pyenv/versions/3.8-dev/lib/python3.8/logging/__init__.py", line 946, in handle
    rv = self.filter(record)
  File "~/.pyenv/versions/3.8-dev/lib/python3.8/logging/__init__.py", line 807, in filter
    result = f.filter(record)
  File "~/python-spanner/.nox/docs/lib/python3.8/site-packages/sphinx/util/logging.py", line 421, in filter
    raise exc
sphinx.errors.SphinxWarning: ~/python-spanner/google/cloud/spanner_v1/types/transaction.py:docstring of google.cloud.spanner_v1.types.TransactionOptions:2:Unexpected section title.

Transactions
============

Warning, treated as error:
~/python-spanner/google/cloud/spanner_v1/types/transaction.py:docstring of google.cloud.spanner_v1.types.TransactionOptions:2:Unexpected section title.

Transactions
============

```

The issue is due to the docstring for [TransactionOptions](https://github.com/larkee/python-spanner/blob/generator-migration/google/cloud/spanner_v1/types/transaction.py#L32). This docstring comes from the [proto comments](https://github.com/larkee/python-spanner/blob/generator-migration/google/cloud/spanner_v1/proto/transaction.proto#L31).

Has this been encountered for other libraries? Is there a recommended way to fix this?

**Comment by busunkim96** [comment]
Proto comments have a limited range of permissible markdown elements. See list: https://cloud.google.com/apis/design/documentation#comment-fmt. Headers are not supported.

I'd recommend removing the `#` from the source protos
