### ISSUE TITLE
Compute library should ignore unknown fields

### ISSUE THREAD

**Issue by igor-solomatov** [googleapis/gapic-generator-python#771]
#### Environment details

  - OS type and version: windows 10 1909
  - Python version: Python 3.8.3
  - pip version: pip 19.2.3
  - `google-cloud-compute` version: 0.1.0

#### Steps to reproduce

  1. compute.RegionsClient().get(project=project_id, region=region)

#### Code example

```python
compute.RegionsClient().get(project=project_id, region=region)
```

#### Stack trace
```
Traceback (most recent call last):
  File "C:\Users\ixs119\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pauseresumedfatool-1.0.0-py3.8.egg\pause_resume_lib\activity_base.py", line 110, in run
  File "C:\Users\ixs119\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pauseresumedfatool-1.0.0-py3.8.egg\pause_resume_lib\activity_base.py", line 49, in initialize
  File "C:\Users\ixs119\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pauseresumedfatool-1.0.0-py3.8.egg\pause_resume_lib\gcp.py", line 69, in list_zone_names_by_region
  File "C:\Users\ixs119\AppData\Local\Programs\Python\Python38-32\lib\site-packages\google\cloud\compute_v1\services\regions\client.py", line 404, in get
    response = rpc(request, retry=retry, timeout=timeout, metadata=metadata,)
  File "C:\Users\ixs119\AppData\Local\Programs\Python\Python38-32\lib\site-packages\google\api_core\gapic_v1\method.py", line 145, in __call__
    return wrapped_func(*args, **kwargs)
  File "C:\Users\ixs119\AppData\Local\Programs\Python\Python38-32\lib\site-packages\google\api_core\grpc_helpers.py", line 57, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "C:\Users\ixs119\AppData\Local\Programs\Python\Python38-32\lib\site-packages\google\cloud\compute_v1\services\regions\transports\rest.py", line 141, in get
    return compute.Region.from_json(response.content)
  File "C:\Users\ixs119\AppData\Local\Programs\Python\Python38-32\lib\site-packages\proto\message.py", line 369, in from_json
    Parse(payload, instance._pb, ignore_unknown_fields=ignore_unknown_fields)
  File "C:\Users\ixs119\AppData\Local\Programs\Python\Python38-32\lib\site-packages\google\protobuf\json_format.py", line 434, in Parse
    return ParseDict(js, message, ignore_unknown_fields, descriptor_pool)
  File "C:\Users\ixs119\AppData\Local\Programs\Python\Python38-32\lib\site-packages\google\protobuf\json_format.py", line 454, in ParseDict
    parser.ConvertMessage(js_dict, message)
  File "C:\Users\ixs119\AppData\Local\Programs\Python\Python38-32\lib\site-packages\google\protobuf\json_format.py", line 485, in ConvertMessage
    self._ConvertFieldValuePair(value, message)
  File "C:\Users\ixs119\AppData\Local\Programs\Python\Python38-32\lib\site-packages\google\protobuf\json_format.py", line 599, in _ConvertFieldValuePair
    raise ParseError(str(e))
google.protobuf.json_format.ParseError: Message type "google.cloud.compute.v1.Region" has no field named "supportsPzs".
 Available Fields(except extensions): ['creationTimestamp', 'deprecated', 'description', 'id', 'kind', 'name', 'quotas', 'selfLink', 'status', 'zones']
```

#### Actual response
Contains new field supportsPzs! Response reducted (removed quotas)

```
{
  "id": "1230",
  "creationTimestamp": "1969-12-31T16:00:00.000-08:00",
  "name": "us-east1",
  "description": "us-east1",
  "status": "UP",
  "zones": [
    "https://www.googleapis.com/compute/v1/projects/dfa-dna-ws0006-us-npe-40b0/zones/us-east1-b",
    "https://www.googleapis.com/compute/v1/projects/dfa-dna-ws0006-us-npe-40b0/zones/us-east1-c",
    "https://www.googleapis.com/compute/v1/projects/dfa-dna-ws0006-us-npe-40b0/zones/us-east1-d"
  ],
  "quotas": [
    {
      "metric": "CPUS",
      "limit": 2400,
      "usage": 31
    }
  ],
  "selfLink": "https://www.googleapis.com/compute/v1/projects/dfa-dna-ws0006-us-npe-40b0/regions/us-east1",
  "supportsPzs": false,
  "kind": "compute#region"
}
```

Can be solved if `return compute.Region.from_json(response.content)` will pass additional parameter `ignore_unknown_fields=True`.

Since it is autgenerated the template needs to be fixed:
https://github.com/googleapis/gapic-generator-python/blob/944136c5ed11af03b1960ac1f0db9f4d0733b381/gapic/templates/%25namespace/%25name_%25version/%25sub/services/%25service/transports/rest.py.j2#L210

Thanks!

**Comment by software-dov** [comment]
Looks like this was fixed by some PR, not obvious which one.
