### ISSUE TITLE
Sphinx Warning introduced with gapic generator version 0.46.3

### ISSUE THREAD

**Issue by parthea** [googleapis/gapic-generator-python#902]
[After updating to gapic generator version 0.46.3](https://github.com/googleapis/python-video-transcoder/pull/50) , there is a sphinx warning. Googlers, see [log here](https://source.cloud.google.com/results/invocations/513c8ac0-7458-4a50-b7a8-78d5d9589ed6/log) .

I resolved the issue in [this commit](https://github.com/googleapis/python-video-transcoder/pull/50/commits/ac0f280cbf42869190ee425124699d2635f24aa5) by adding a new line [here](https://github.com/googleapis/googleapis-gen/blob/master/google/cloud/video/transcoder/v1beta1/video-transcoder-v1beta1-py/google/cloud/video/transcoder_v1beta1/types/resources.py#L564).

 
```

Traceback (most recent call last):
  File "/tmpfs/src/github/python-video-transcoder/.nox/docs/lib/python3.8/site-packages/sphinx/cmd/build.py", line 280, in build_main
    app.build(args.force_all, filenames)
  File "/tmpfs/src/github/python-video-transcoder/.nox/docs/lib/python3.8/site-packages/sphinx/application.py", line 350, in build
    self.builder.build_update()
  File "/tmpfs/src/github/python-video-transcoder/.nox/docs/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 292, in build_update
    self.build(to_build,
  File "/tmpfs/src/github/python-video-transcoder/.nox/docs/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 306, in build
    updated_docnames = set(self.read())
  File "/usr/local/lib/python3.8/contextlib.py", line 120, in __exit__
    next(self.gen)
  File "/tmpfs/src/github/python-video-transcoder/.nox/docs/lib/python3.8/site-packages/sphinx/util/logging.py", line 213, in pending_warnings
    memhandler.flushTo(logger)
  File "/tmpfs/src/github/python-video-transcoder/.nox/docs/lib/python3.8/site-packages/sphinx/util/logging.py", line 178, in flushTo
    logger.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1587, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1649, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 946, in handle
    rv = self.filter(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 807, in filter
    result = f.filter(record)
  File "/tmpfs/src/github/python-video-transcoder/.nox/docs/lib/python3.8/site-packages/sphinx/util/logging.py", line 423, in filter
    raise exc
sphinx.errors.SphinxWarning: /tmpfs/src/github/python-video-transcoder/google/cloud/video/transcoder_v1beta1/types/resources.py:docstring of google.cloud.video.transcoder_v1beta1.types.resources.SpriteSheet:1:Unknown target name: "format".

Warning, treated as error:
/tmpfs/src/github/python-video-transcoder/google/cloud/video/transcoder_v1beta1/types/resources.py:docstring of google.cloud.video.transcoder_v1beta1.types.resources.SpriteSheet:1:Unknown target name: "format".
```

**Comment by software-dov** [comment]
Unable to recreate on latest
