### ISSUE TITLE
Python generator cannot accept LRO metadata from a different proto namespace

### ISSUE THREAD

**Issue by parthea** [googleapis/gapic-generator-python#932]
In the [Filestore v1 BUILD.bazel file](https://github.com/googleapis/googleapis/blob/master/google/cloud/filestore/v1/BUILD.bazel#L167), the build rules for python are commented out with the following note.

> Python generator cannot accept LRO metadata from a different proto namespace.

**Comment by danoscarmike** [comment]
@hkdevandla for vis

**Comment by hkdevandla** [comment]
Hi @alexander-fenster, can you please triage this? Not sure why this is issue only for python but not other languages. Or is this something that needs to be addressed overall for all languages? Thanks!

**Comment by hkdevandla** [comment]
There work required in generators to support this LRO metadata type. We will address this in coming cycles.

**Comment by hkdevandla** [comment]
@alexander-fenster , can you check if we can plan for this work in the September sprint?
@software-dov (for vis)

**Comment by danoscarmike** [comment]
@hkdevandla @alexander-fenster this is on the critical path now. Can we prioritize?

**Comment by noahdietz** [comment]
Some more debugging notes. Adding the import statement for `google/cloud/common/operation_metadata.proto` and running the python build target referenced above results in the following error & stack trace:
```
Traceback (most recent call last):
  File "/usr/local/google/home/ndietz/.cache/bazel/_bazel_ndietz/9bee9ec457d61e9cf6dd8d5b5797a116/sandbox/linux-sandbox/1729/execroot/com_google_googleapis/bazel-out/host/bin/external/gapic_generator_python/gapic_plugin.runfiles/gapic_generator_python/gapic/cli/generate.py", line 71, in <module>
    generate()
  File "/usr/local/google/home/ndietz/.cache/bazel/_bazel_ndietz/9bee9ec457d61e9cf6dd8d5b5797a116/sandbox/linux-sandbox/1729/execroot/com_google_googleapis/bazel-out/host/bin/external/gapic_generator_python/gapic_plugin.runfiles/gapic_generator_python_pip_deps/pypi__click/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/google/home/ndietz/.cache/bazel/_bazel_ndietz/9bee9ec457d61e9cf6dd8d5b5797a116/sandbox/linux-sandbox/1729/execroot/com_google_googleapis/bazel-out/host/bin/external/gapic_generator_python/gapic_plugin.runfiles/gapic_generator_python_pip_deps/pypi__click/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/usr/local/google/home/ndietz/.cache/bazel/_bazel_ndietz/9bee9ec457d61e9cf6dd8d5b5797a116/sandbox/linux-sandbox/1729/execroot/com_google_googleapis/bazel-out/host/bin/external/gapic_generator_python/gapic_plugin.runfiles/gapic_generator_python_pip_deps/pypi__click/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/google/home/ndietz/.cache/bazel/_bazel_ndietz/9bee9ec457d61e9cf6dd8d5b5797a116/sandbox/linux-sandbox/1729/execroot/com_google_googleapis/bazel-out/host/bin/external/gapic_generator_python/gapic_plugin.runfiles/gapic_generator_python_pip_deps/pypi__click/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/google/home/ndietz/.cache/bazel/_bazel_ndietz/9bee9ec457d61e9cf6dd8d5b5797a116/sandbox/linux-sandbox/1729/execroot/com_google_googleapis/bazel-out/host/bin/external/gapic_generator_python/gapic_plugin.runfiles/gapic_generator_python/gapic/cli/generate.py", line 59, in generate
    api_schema = api.API.build(req.proto_file, opts=opts, package=package)
  File "/usr/local/google/home/ndietz/.cache/bazel/_bazel_ndietz/9bee9ec457d61e9cf6dd8d5b5797a116/sandbox/linux-sandbox/1729/execroot/com_google_googleapis/bazel-out/host/bin/external/gapic_generator_python/gapic_plugin.runfiles/gapic_generator_python/gapic/schema/api.py", line 255, in build
    naming = api_naming.Naming.build(*filter(
  File "/usr/local/google/home/ndietz/.cache/bazel/_bazel_ndietz/9bee9ec457d61e9cf6dd8d5b5797a116/sandbox/linux-sandbox/1729/execroot/com_google_googleapis/bazel-out/host/bin/external/gapic_generator_python/gapic_plugin.runfiles/gapic_generator_python/gapic/schema/naming.py", line 125, in build
    raise ValueError('All protos must have the same proto package '
ValueError: All protos must have the same proto package up to and including the version.
--python_gapic_out: protoc-gen-python_gapic: Plugin failed with status code 1.
```

**Comment by parthea** [comment]
@noahdietz  I was able to solve the error `All protos must have the same proto package` locally by changing [this line](https://github.com/googleapis/googleapis/blob/master/google/cloud/filestore/v1/BUILD.bazel#L178) from
```
    srcs = [":filestore_proto_with_info"],
```
to
```
    srcs = [":filestore_proto"],
```

**Comment by noahdietz** [comment]
Interesting. And so the Python gapic was generated properly as a result?

**Comment by noahdietz** [comment]
I was jsut able to reproduce this. I wonder why that is...

**Comment by parthea** [comment]
Python gapic was generated but I'm not able to import the client see stack trace below. I'm wondering if the next step is to add [google/cloud/common/operation_metadata.proto](https://github.com/googleapis/googleapis/blob/master/google/cloud/common/operation_metadata.proto) to https://github.com/googleapis/python-api-common-protos/tree/main/google and add `googleapis-common-protos` as a python dependency.

```
partheniou@partheniou-vm-1:~/git/python-filestore$ python3
Python 3.6.13 (default, Jun  3 2021, 19:45:51) 
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from google.cloud import filestore
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/google/home/partheniou/git/python-filestore/google/cloud/filestore/__init__.py", line 17, in <module>
    from google.cloud.filestore_v1.services.cloud_filestore_manager.client import (
  File "/usr/local/google/home/partheniou/git/python-filestore/google/cloud/filestore_v1/__init__.py", line 17, in <module>
    from .services.cloud_filestore_manager import CloudFilestoreManagerClient
  File "/usr/local/google/home/partheniou/git/python-filestore/google/cloud/filestore_v1/services/cloud_filestore_manager/__init__.py", line 16, in <module>
    from .client import CloudFilestoreManagerClient
  File "/usr/local/google/home/partheniou/git/python-filestore/google/cloud/filestore_v1/services/cloud_filestore_manager/client.py", line 35, in <module>
    from google.cloud.common import operation_metadata_pb2  # type: ignore
ModuleNotFoundError: No module named 'google.cloud.common'
```

**Comment by parthea** [comment]
The issue is resolved. (I forgot to close the bug.)
